---
- name: Check if structure configuration file exists
  tags: [build, provision]
  stat:
    path: '{{ root_dir }}/intended/structured_configs//{{ inventory_hostname }}.yml'
  register: stat_result
  delegate_to: localhost

- name: Include device intended structure configuration variables
  include_vars: '{{ root_dir }}/intended/structured_configs//{{ inventory_hostname }}.yml'
  delegate_to: localhost
  tags: [build, provision]
  when: stat_result.stat.exists

- name: Generate eos intended configuration
  template:
    src: eos-intended-config.j2
    dest: '{{ root_dir }}/intended/configs/{{ inventory_hostname }}.cfg'
  delegate_to: localhost
  register: eosconfig
  tags: [build, provision]

- name: Generate device documentation
  template:
    src: eos-device-documentation.j2
    dest: '{{ root_dir }}/documentation/devices/{{ inventory_hostname }}.md'
  delegate_to: localhost
  tags: [build, provision]
