---
- name: Converge
  hosts: all
  gather_facts: false
  connection: local
  tasks:

    - name: generate intented variables
      delegate_to: 127.0.0.1
      import_role:
         name: arista.avd.eos_l3ls_evpn
