## Ansible Generated ##

### DC1-L2LEAF2A ###


### Leaf Info ###
l2leaf_node_group: DC1_L2LEAF2
switch_platform: vEOS-LAB
leaf_id: 9
switch_mgmt_ip: 192.168.200.113/24
leaf_filter_tenants: ['all']
leaf_filter_tags: ['all']
leaf_allowed_vrfs: []
leaf_allowed_svis: []
leaf_allowed_vlans: []
leaf_mlag: True
leaf_mlag_group: DC1_L2LEAF2
leaf_mlag_role: primary
leaf_mlag_peer: DC1-L2LEAF2B
leaf_mlag_ip: 16
leaf_mlag_peer_ip: 17
leaf_mlag_peer_id: 10

service_routing_protocols_model: multi-agent
ip_routing: true

### Hardware Counter
hardware_counters:

### Daemon TerminAttr
daemon_terminattr:
  ingestgrpcurl:
    ips:
      - 192.168.200.11
    port: 9910
  ingestauth_key: telarista
  ingestvrf: MGMT
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"

vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199

### Event Monitor ###
event_monitor:

### Event Handler ###
event_handlers:

### Load Interval ###
load_interval:

### Queue Monitor Lenght ###
queue_monitor_length:

### Name Servers ###
name_server:
  source:
    vrf: MGMT
  nodes:
    - 192.168.200.5
    - 8.8.8.8

### NTP Servers ###
ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
    - 192.168.200.5

### Redundancy ###
redundancy:

### Spanning-tree ###
spanning_tree:
  mode: mstp
  priority: 16384
  no_spanning_tree_vlan: 4094


### AAA authorization ###
aaa_authorization:

### local users ###
local_users:
  admin:
    privilege: 15
    role: network-admin
    no_password: True
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.

### Clock Timezone ###
clock:

### VLANs ###
vlans:
## mlag vlans ##
  4094:
    tenant: system
    name: MLAG_PEER
    trunk_groups:
      - MLAG

## fake_tenant ##

### VRFs ###
vrfs:
  MGMT:
    ip_routing: False
### Port-Channel Interfaces ###
port_channel_interfaces:
  Port-Channel1:
    description: DC1-SVC3A_Po7
    vlans: 
    mode: trunk
    mlag: 1
## mlag peer-link ##
  Port-Channel3:
    description: MLAG_PEER_DC1-L2LEAF2B_Po3
    vlans: "2-4094"
    mode: trunk
    trunk_groups:
      - MLAG

### Ethernet Interfaces ###
ethernet_interfaces:
## L3 LEAF link ##
  Ethernet1:
    peer: DC1-SVC3A
    peer_interface: Ethernet7
    peer_type: l3leaf
    description: DC1-SVC3A_Ethernet7
    channel_group:
      id: 1
      mode: active
## L3 LEAF link ##
  Ethernet2:
    peer: DC1-SVC3B
    peer_interface: Ethernet7
    peer_type: l3leaf
    description: DC1-SVC3B_Ethernet7
    channel_group:
      id: 1
      mode: active
## mlag interfaces ##
  Ethernet3:
    peer: DC1-L2LEAF2B
    peer_interface: Ethernet3
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-L2LEAF2B_Ethernet3
    channel_group:
      id: 3
      mode: active
  Ethernet4:
    peer: DC1-L2LEAF2B
    peer_interface: Ethernet4
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-L2LEAF2B_Ethernet4
    channel_group:
      id: 3
      mode: active

### Management Interfaces ###
management_interfaces:
  Management1:
    description: oob_management
    vrf: MGMT
    ip_address: 192.168.200.113/24
    gateway: 192.168.200.5

### VLAN Interfaces ###
vlan_interfaces:
  Vlan4094:
    description: MLAG_PEER
    ip_address: 10.255.252.16/31
    no_autostate: true
    mtu: 1500

### TCAM Profiles ###
tcam_profile:

### MAC address table ###
mac_address_table:

ip_igmp_snooping:
  globally_enabled: True
  vlans:
## fake_tenant ##

### static routes ###
static_routes:
  - vrf: MGMT
    destination_address_prefix: 0.0.0.0/0
    gateway: 192.168.200.5

### MLAG Configuration ###
mlag_configuration:
  domain_id: DC1_L2LEAF2
  local_interface: Vlan4094
  peer_address: 10.255.252.17
  peer_address_heartbeat:
    peer_ip: 192.168.200.114
    vrf: MGMT
  dual_primary_detection_delay: 5
  peer_link: Port-Channel3
  reload_delay_mlag: 300
  reload_delay_non_mlag: 330

### Queue Monitor Streaming ###
queue_monitor_streaming:

### Management API http ###
management_api_http:
  enable_https: True
  enable_vrfs:
    MGMT:
