## Ansible Generated ##

### DC1-L2LEAF1A ###


### Leaf Info ###
l2leaf_node_group: DC1_L2LEAF1
switch_platform: vEOS-LAB
leaf_id: 8
switch_mgmt_ip: 192.168.200.112/24
leaf_filter_tenants: ['Tenant_A']
leaf_filter_tags: ['opzone', 'web', 'app']
leaf_allowed_vrfs: []
leaf_allowed_svis: []
leaf_allowed_vlans: []
leaf_mlag: False

service_routing_protocols_model: multi-agent
ip_routing: true

### Hardware Counter
hardware_counters:

### Daemon TerminAttr
daemon_terminattr:
  ingestgrpcurl:
    ips:
      - 192.168.200.11
    port: 9910
  ingestauth_key: telarista
  ingestvrf: MGMT
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"

vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199

### Event Monitor ###
event_monitor:

### Event Handler ###
event_handlers:

### Load Interval ###
load_interval:

### Queue Monitor Lenght ###
queue_monitor_length:

### Name Servers ###
name_server:
  source:
    vrf: MGMT
  nodes:
    - 192.168.200.5
    - 8.8.8.8

### NTP Servers ###
ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
    - 192.168.200.5

### Redundancy ###
redundancy:

### Spanning-tree ###
spanning_tree:
  mode: mstp
  priority: 16384


### AAA authorization ###
aaa_authorization:

### local users ###
local_users:
  admin:
    privilege: 15
    role: network-admin
    no_password: True
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.

### Clock Timezone ###
clock:

### VLANs ###
vlans:


### VRFs ###
vrfs:
  MGMT:
    ip_routing: False
### Port-Channel Interfaces ###
port_channel_interfaces:
  Port-Channel1:
    description: DC1-LEAF2A_Po7
    vlans: 
    mode: trunk
    mlag: 1

### Ethernet Interfaces ###
ethernet_interfaces:
## L3 LEAF link ##
  Ethernet1:
    peer: DC1-LEAF2A
    peer_interface: Ethernet7
    peer_type: l3leaf
    description: DC1-LEAF2A_Ethernet7
    channel_group:
      id: 1
      mode: active
## L3 LEAF link ##
  Ethernet2:
    peer: DC1-LEAF2B
    peer_interface: Ethernet7
    peer_type: l3leaf
    description: DC1-LEAF2B_Ethernet7
    channel_group:
      id: 1
      mode: active

### Management Interfaces ###
management_interfaces:
  Management1:
    description: oob_management
    vrf: MGMT
    ip_address: 192.168.200.112/24
    gateway: 192.168.200.5

### VLAN Interfaces ###
vlan_interfaces:

### TCAM Profiles ###
tcam_profile:

### MAC address table ###
mac_address_table:

ip_igmp_snooping:
  globally_enabled: True
  vlans:

### static routes ###
static_routes:
  - vrf: MGMT
    destination_address_prefix: 0.0.0.0/0
    gateway: 192.168.200.5


### Queue Monitor Streaming ###
queue_monitor_streaming:

### Management API http ###
management_api_http:
  enable_https: True
  enable_vrfs:
    MGMT:
