### Routing - PIM Sparse Mode ###
router_pim_sparse_mode:
  ipv4:
    rp_addresses:
      10.238.1.161:
        groups:
          239.12.12.12/32:
          239.12.12.13/32:
          239.12.12.14/32:
          239.12.12.16/32:
          239.12.12.20/32:
          239.12.12.21/32:
    anycast_rps:
      10.38.1.161:
        other_anycast_rp_addresses:
          10.50.64.16:
            register_count: 15
