---
### Port-Channel Interfaces ###
port_channel_interfaces:
  Port-Channel5:
    description: DC1_L2LEAF1_Po1
    vlans: 110,201
    mode: trunk
    mlag: 5


  Port-Channel3:
    description: MLAG_PEER_DC1-LEAF1B_Po3
    vlans: "2-4094"
    mode: trunk
    trunk_groups:
      - LEAF_PEER_L3
      - MLAG

  Port-Channel50:
    description: SRV-POD03_PortChanne1
    vlans: 1-4000
    mode: trunk
    esi: 0000:0000:0303:0202:0101
    rt: 03:03:02:02:01:01
    lacp_id: 0303.0202.0101

# Children interfaces
ethernet_interfaces:
  Ethernet5:
    peer: DC1-AGG01
    peer_interface: Ethernet1
    peer_type: l2leaf
    description: DC1-AGG01_Ethernet1
    channel_group:
      id: 5
      mode: active

  Ethernet3:
    peer: DC1-LEAF1B
    peer_interface: Ethernet3
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-LEAF1B_Ethernet3
    channel_group:
      id: 3
      mode: active

  Ethernet4:
    peer: DC1-LEAF1B
    peer_interface: Ethernet4
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-LEAF1B_Ethernet4
    channel_group:
      id: 3
      mode: active

  Ethernet50:
    peer: SRV-POD03
    peer_interface: Eth1
    peer_type: server
    description: SRV-POD03_Eth1
    mode: trunk
    vlans: 1-4000
    channel_group:
      id: 5
      mode: "active"
    profile: ALL