---
static_routes:
  - vrf: default
    destination_address_prefix: 1.1.1.0/24
    interface: vlan101
    gateway: 10.1.1.1

  - vrf: default
    destination_address_prefix: 1.1.2.0/24
    interface: vlan101
    gateway: 10.1.1.1
    distance: 200
    tag: 666
    name: RT-TO-FAKE-DMZ

  - vrf: customer01
    destination_address_prefix: 1.2.1.0/24
    interface: vlan202
    gateway: 10.1.2.1

  - vrf: customer01
    destination_address_prefix: 1.2.2.0/24
    interface: vlan101
    gateway: 10.1.2.1
    distance: 201
    tag: 667
    name: RT-TO-FAKE-DMZ


ipv6_static_routes:
  - vrf: default
    destination_address_prefix: 2a01:cb04:4e6:d300::/64
    interface: vlan101
    gateway: 2a01:cb04:4e6:d100::1

  - vrf: default
    destination_address_prefix: 2a01:cb04:4e6:d400::/64
    interface: vlan101
    gateway: 2a01:cb04:4e6:d100::1
    distance: 200
    tag: 666
    name: RT-TO-FAKE-DMZ

  - vrf: default
    destination_address_prefix: 2a01:cb04:4e6:d400::/64
    interface: vlan101
    gateway: 2a01:cb04:4e6:d100::1
    distance: 200
    tag: 666
    metric: 100
    name: RT-TO-FAKE-DB-ZONE

  - vrf: customer01
    destination_address_prefix: 2a01:cb04:4e6:a300::/64
    interface: vlan101
    gateway: 2a01:cb04:4e6:100::1

  - vrf: customer01
    destination_address_prefix: 2a01:cb04:4e6:a400::/64
    interface: vlan101
    gateway: 2a01:cb04:4e6:100::1
    distance: 201
    tag: 667
    name: RT-TO-FAKE-DMZ