router_bgp:
  as: 65101
  router_id: 192.168.255.3
  bgp_defaults:
    - no bgp default ipv4-unicast
    - distance bgp 20 200 200
    - graceful-restart restart-time 300
    - graceful-restart
    - maximum-paths 2 ecmp 2
  peer_groups:
    EVPN-OVERLAY-PEERS:
      type: evpn
      remote_as: 65001
      update_source: Loopback0
      bfd: true
      ebgp_multihop: 3
      password: "q+VNViP5i4rVjW1cxFv2wA=="
      send_community: true
      maximum_routes: 0
  neighbors:
    192.168.255.1:
      peer_group: EVPN-OVERLAY-PEERS
    192.168.255.2:
      peer_group: EVPN-OVERLAY-PEERS
  redistribute_routes:
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
      MLAG-IPv4-UNDERLAY-PEER:
        activate: false
  address_family_ipv4:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: false
  vlan_aware_bundles:
## Tenant_A ##
    TENANT_A_PROJECT01:
      rd: "192.168.255.3:11"
      route_targets:
        both:
          - "11:11"
      redistribute_routes:
        - learned
      vlan: 110
    TENANT_A_PROJECT02:
      rd: "192.168.255.3:12"
      route_targets:
        both:
          - "12:12"
      redistribute_routes:
        - learned
      vlan: 112
## Tenant_B ##
    B-ELAN-201:
      tenant: Tenant_B
      rd: "192.168.255.3:20201"
      route_targets:
        both:
          - "20201:20201"
      redistribute_routes:
        - learned
      vlan: 201
  vlans:
  vrfs:
## Tenant_A ##
    TENANT_A_PROJECT01:
      router_id: 192.168.255.3
      rd: "192.168.255.3:11"
      route_targets:
        import:
          evpn:
            - "11:11"
        export:
          evpn:
            - "11:11"
      neighbors:
        10.255.251.1:
          peer_group: MLAG-IPv4-UNDERLAY-PEER
      redistribute_routes:
        - connected
    TENANT_A_PROJECT02:
      router_id: 192.168.255.3
      rd: "192.168.255.3:12"
      route_targets:
        import:
          evpn:
            - "12:12"
        export:
          evpn:
            - "12:12"
      neighbors:
        10.255.251.1:
          peer_group: MLAG-IPv4-UNDERLAY-PEER
      redistribute_routes:
        - connected
