### VLAN Interfaces ###
vlan_interfaces:
# Standard SVI configuration
  Vlan2001:
    description: SVI Description
    vrf: Tenant_B
    ip_address_virtual: 10.2.1.1/24

  Vlan2002:
    description: SVI Description
    vrf: Tenant_B
    ip_address_virtual: 10.2.2.1/24

  Vlan83:
    description: SVI Description
    shutdown: false
    ip_address_virtual: 10.10.83.1/24

  Vlan84:
    description: SVI Description
    ip_address_virtual: 10.10.84.1/24

  Vlan85:
    description: SVI Description
    ip_address: 10.10.84.1/24

  Vlan87:
    description: SVI Description
    shutdown: true
    ip_router_virtual_address: 10.10.87.254
    ip_address: 10.10.87.1/24
    access_group_in: ACL_IN
    access_group_out: ACL_OUT

  Vlan88:
    description: SVI Description
    shutdown: true
    ip_address_virtual: 10.10.87.1/23

# MCAST Configuration

  Vlan4094:
    description: SVI Description
    ip_address: 169.254.252.0/31
    ipv6_address_link_local: fe80::a/64
    mtu: 9214
    pim:
      ipv4:
        sparse_mode: true

# Helpers on SVI

  Vlan41:
    description: SVI Description
    shutdown: false
    ip_address_virtual: 10.10.41.1/24
    ip_helpers:
      10.10.96.151:
        source_interface: Loopback0
      10.10.96.150:
        source_interface: Loopback0
      10.10.64.150:
        source_interface: Loopback0

  Vlan42:
    description: SVI Description
    shutdown: false
    ip_address_virtual: 10.10.42.1/24
    helpers:
      10.10.96.151:
        source_interface: Loopback0
      10.10.96.150:
        source_interface: Loopback0
      10.10.64.150:
        source_interface: Loopback0

# IPv6 SVI configuration

  Vlan501:
    description: SVI Description
    shutdown: false
    ip_address: 10.50.26.29/27
    ipv6_address: 1b11:3a00:22b0:0088::207/127
    ipv6_nd_ra_disabled: true

  Vlan1001:
    description: SVI Description
    shutdown: false
    vrf: Tenant_A
    ip_address_virtual: 10.1.1.1/24
    ipv6_address: a1::1/64
    ipv6_nd_managed_config_flag: true
    ipv6_nd_prefixes:
      a1::/64:
        valid_lifetime: infinite
        preferred_lifetime: infinite
        no_autoconfig_flag: true

  Vlan24:
    description: SVI Description
    shutdown: false
    ip_address_virtual: 10.10.24.1/24
    ipv6_address: 1b11:3a00:22b0:6::15/64
    ipv6_nd_managed_config_flag: true
    ipv6_nd_prefixes:
      1b11:3a00:22b0:6::/64:
        valid_lifetime: infinite
        preferred_lifetime: infinite
        no_autoconfig_flag: true
    ipv6_virtual_router_address: 1b11:3a00:22b0:6::1

  Vlan1002:
    description: SVI Description
    shutdown: false
    vrf: Tenant_A
    ip_address_virtual: 10.1.2.1/24
    ipv6_address: a2::1/64
    ipv6_nd_managed_config_flag: true
    ipv6_nd_prefixes:
      a2::/64:
        valid_lifetime: infinite
        preferred_lifetime: infinite
        no_autoconfig_flag: true
    ipv6_nd_ra_disabled: true

  Vlan75:
    description: SVI Description
    shutdown: false
    ip_address_virtual: 10.10.75.1/24
    ipv6_address: 1b11:3a00:22b0:1000::15/64
    ipv6_nd_managed_config_flag: true
    ipv6_nd_prefixes:
      1b11:3a00:22b0:1000::/64:
        valid_lifetime: infinite
        preferred_lifetime: infinite
        no_autoconfig_flag: true
    ipv6_virtual_router_address: 1b11:3a00:22b0:1000::1

# IPv6 + helpers + Mcast

  Vlan89:
    description: SVI Description
    shutdown: false
    ip_address_virtual: 10.10.144.3/20
    ipv6_address: 1b11:3a00:22b0:5200::15/64
    ipv6_nd_managed_config_flag: true
    ipv6_nd_prefixes:
      1b11:3a00:22b0:5200::/64:
        valid_lifetime: infinite
        preferred_lifetime: infinite
        no_autoconfig_flag: true
    ipv6_virtual_router_address: 1b11:3a00:22b0:5200::3
    helpers:
      10.10.96.101:
        source_interface: Loopback0
      10.10.96.151:
        source_interface: Loopback0
      10.10.96.150:
        source_interface: Loopback0
      10.10.64.150:
        source_interface: Loopback0
    multicast:
      ipv4:
        source_route_export:
          enabled: true
    pim:
      ipv4:
        sparse_mode: true
        local_interface: Loopback0
