---
- name: Upgrade from v1.0 to v1.1
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Upgrade AVD datamodel from v1.0 to v1.1
      run_once: true
      include_role:
        name: arista.avd.upgrade_tools
      vars:
        subset: 'v1.0_to_v1.1'
      loop:
        - DC1_TENANTS_NETWORKS.yml
    # - name: Deploy new file version
    #   delegate_to: 127.0.0.1
    #   run_once: true
    #   copy:
    #     src: '{{ playbook_dir }}/inventory/upgrade_1.0_to_1.1/group_vars/DC1_TENANTS_NETWORKS.yml'
    #     dest: '{{ playbook_dir }}/inventory/group_vars/DC1_TENANTS_NETWORKS.yml'
